name: Unit tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: npm ci
      run: npm ci
    
    - run: npm run test
      name: npm run test
